// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: contact.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createContact = `-- name: CreateContact :one
INSERT INTO public.contact (username, given_name, email, birthday_date, group_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, given_name, email, birthday_date, group_id
`

type CreateContactParams struct {
	Username     string        `json:"username"`
	GivenName    string        `json:"given_name"`
	Email        string        `json:"email"`
	BirthdayDate time.Time     `json:"birthday_date"`
	GroupID      uuid.NullUUID `json:"group_id"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, createContact,
		arg.Username,
		arg.GivenName,
		arg.Email,
		arg.BirthdayDate,
		arg.GroupID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.GivenName,
		&i.Email,
		&i.BirthdayDate,
		&i.GroupID,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM public.contact
WHERE id = $1
`

func (q *Queries) DeleteContact(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteContact, id)
	return err
}

const getContact = `-- name: GetContact :one
SELECT id, username, given_name, email, birthday_date, group_id FROM public.contact
WHERE id = $1
`

func (q *Queries) GetContact(ctx context.Context, id uuid.UUID) (Contact, error) {
	row := q.db.QueryRowContext(ctx, getContact, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.GivenName,
		&i.Email,
		&i.BirthdayDate,
		&i.GroupID,
	)
	return i, err
}

const updateContact = `-- name: UpdateContact :one
UPDATE public.contact
SET
    username = $2,
    given_name = $3,
    email = $4,
    birthday_date = $5,
    group_id = $6
WHERE id = $1
RETURNING id, username, given_name, email, birthday_date, group_id
`

type UpdateContactParams struct {
	ID           uuid.UUID     `json:"id"`
	Username     string        `json:"username"`
	GivenName    string        `json:"given_name"`
	Email        string        `json:"email"`
	BirthdayDate time.Time     `json:"birthday_date"`
	GroupID      uuid.NullUUID `json:"group_id"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, updateContact,
		arg.ID,
		arg.Username,
		arg.GivenName,
		arg.Email,
		arg.BirthdayDate,
		arg.GroupID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.GivenName,
		&i.Email,
		&i.BirthdayDate,
		&i.GroupID,
	)
	return i, err
}
