// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: group.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO public."group" (title, descriptions)
VALUES ($1, $2)
RETURNING id, title, descriptions
`

type CreateGroupParams struct {
	Title        string `json:"title"`
	Descriptions string `json:"descriptions"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.Title, arg.Descriptions)
	var i Group
	err := row.Scan(&i.ID, &i.Title, &i.Descriptions)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM public."group"
WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, title, descriptions FROM public."group"
WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i Group
	err := row.Scan(&i.ID, &i.Title, &i.Descriptions)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE public."group"
SET
    title = $2,
    descriptions = $3
WHERE id = $1
RETURNING id, title, descriptions
`

type UpdateGroupParams struct {
	ID           uuid.UUID `json:"id"`
	Title        string    `json:"title"`
	Descriptions string    `json:"descriptions"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, updateGroup, arg.ID, arg.Title, arg.Descriptions)
	var i Group
	err := row.Scan(&i.ID, &i.Title, &i.Descriptions)
	return i, err
}
