// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"time"
	"github.com/google/uuid"
)

type Contact struct {
	ID           uuid.UUID     `json:"id"`
	Username     string        `json:"username"`
	GivenName    string        `json:"given_name"`
	Email        string        `json:"email"`
	BirthdayDate time.Time     `json:"birthday_date"`
	GroupID      uuid.NullUUID `json:"group_id"`
}

type Group struct {
	ID           uuid.UUID `json:"id"`
	Title        string    `json:"title"`
	Descriptions string    `json:"descriptions"`
}

type Phone struct {
	ID          uuid.UUID     `json:"id"`
	CountryCode int32         `json:"country_code"`
	Operator    int32         `json:"operator"`
	Number      int64         `json:"number"`
	ContactID   uuid.NullUUID `json:"contact_id"`
}
