// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: phone.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPhone = `-- name: CreatePhone :one
INSERT INTO public.phone (country_code, operator, "number", contact_id)
VALUES ($1, $2, $3, $4)
RETURNING id, country_code, operator, number, contact_id
`

type CreatePhoneParams struct {
	CountryCode int32         `json:"country_code"`
	Operator    int32         `json:"operator"`
	Number      int64         `json:"number"`
	ContactID   uuid.NullUUID `json:"contact_id"`
}

func (q *Queries) CreatePhone(ctx context.Context, arg CreatePhoneParams) (Phone, error) {
	row := q.db.QueryRowContext(ctx, createPhone,
		arg.CountryCode,
		arg.Operator,
		arg.Number,
		arg.ContactID,
	)
	var i Phone
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.Operator,
		&i.Number,
		&i.ContactID,
	)
	return i, err
}

const deletePhone = `-- name: DeletePhone :exec
DELETE FROM public.phone
WHERE id = $1
`

func (q *Queries) DeletePhone(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePhone, id)
	return err
}

const getPhone = `-- name: GetPhone :one
SELECT id, country_code, operator, number, contact_id FROM public.phone
WHERE id = $1
`

func (q *Queries) GetPhone(ctx context.Context, id uuid.UUID) (Phone, error) {
	row := q.db.QueryRowContext(ctx, getPhone, id)
	var i Phone
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.Operator,
		&i.Number,
		&i.ContactID,
	)
	return i, err
}

const updatePhone = `-- name: UpdatePhone :one
UPDATE public.phone
SET
    country_code = $2,
    operator = $3,
    "number" = $4,
    contact_id = $5
WHERE id = $1
RETURNING id, country_code, operator, number, contact_id
`

type UpdatePhoneParams struct {
	ID          uuid.UUID     `json:"id"`
	CountryCode int32         `json:"country_code"`
	Operator    int32         `json:"operator"`
	Number      int64         `json:"number"`
	ContactID   uuid.NullUUID `json:"contact_id"`
}

func (q *Queries) UpdatePhone(ctx context.Context, arg UpdatePhoneParams) (Phone, error) {
	row := q.db.QueryRowContext(ctx, updatePhone,
		arg.ID,
		arg.CountryCode,
		arg.Operator,
		arg.Number,
		arg.ContactID,
	)
	var i Phone
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.Operator,
		&i.Number,
		&i.ContactID,
	)
	return i, err
}
