// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreatePhone(ctx context.Context, arg CreatePhoneParams) (Phone, error)
	DeleteContact(ctx context.Context, id uuid.UUID) error
	DeleteGroup(ctx context.Context, id uuid.UUID) error
	DeletePhone(ctx context.Context, id uuid.UUID) error
	GetContact(ctx context.Context, id uuid.UUID) (Contact, error)
	GetGroup(ctx context.Context, id uuid.UUID) (Group, error)
	GetPhone(ctx context.Context, id uuid.UUID) (Phone, error)
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdatePhone(ctx context.Context, arg UpdatePhoneParams) (Phone, error)
}

var _ Querier = (*Queries)(nil)
